// qt_learn/vue/music/src/components/tab.vue
<template>
  <div class="tab">
    <router-link tag="div" class="tab-item" to="/recommend">
      <span class="tab-link">推荐</span>
    </router-link>
    <router-link tag="div" class="tab-item" to="/singer">
      <span class="tab-link">歌手</span>
    </router-link>
    <router-link tag="div" class="tab-item" to="/rank">
      <span class="tab-link">排行</span>
    </router-link>
    <router-link tag="div" class="tab-item" to="/search">
      <span class="tab-link">搜索</span>
    </router-link>
  </div>
</template>

<script type="text/ecmascript-6">
export default {
  name: 'tab'
}
</script>

<style scoped lang="stylus">
@import '../assets/css/function'
.tab
  display flex
  height px2rem(88px)
  line-height px2rem(88px)
  font-size 14px
  &-item
    flex 1
    text-align center
    color hsla(0, 0%, 100%, 0.5)
    .tab-link
      padding-bottom 5px
  .router-link-active
    .tab-link
      color #ea2448
      border-bottom 2px solid #ea2448
</style>

// qt_learn/Demo/music/src/components/tab/Tab.tsx
import * as React from 'react';
import { NavLink } from 'react-router-dom'
import { Component } from 'react';
import './Tab.scss';


class Tab extends Component{
  render() {
      // console.log("Header render")
      return (
          <div className="tab">
            <NavLink to="/recommend" className="tab-item" activeClassName="link-selected">
              <span className="tab-link">推荐</span>
            </NavLink>
            <NavLink to="/singer" className="tab-item" activeClassName="link-selected">
              <span className="tab-link">歌手</span>
            </NavLink>
            <NavLink to="/rank" className="tab-item" activeClassName="link-selected">
              <span className="tab-link">排行
            </span>
            </NavLink>
            <NavLink to="/search" className="tab-item" activeClassName="link-selected">
              <span className="tab-link">搜索</span>
            </NavLink>
          </div>
      )
  }
}

export default Tab
